version: "3.9"

services:
  database:
    image: mysql:5.7
    container_name: sales_Database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'sales'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - my-db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salesAPI
    command: npm run dev
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database

volumes:
  my-db:
    driver: local